Repository auth0/lock, pull requests merged in 2018-03, with the labels that each got.

#1288 Fix inconsistent screen title
  src/core/screen.js
Labels: CH: Fixed

#1278 Making HRD work in signup page and showing an error when HRD is detected in the forgot password page
  scripts/complete-translations.js
  src/connection/database/reset_password.jsx
  src/engine/classic/sign_up_screen.jsx
  src/i18n/af.js
  src/i18n/ca.js
  src/i18n/cs.js
  src/i18n/da.js
  src/i18n/de.js
  src/i18n/en.js
  src/i18n/es.js
  src/i18n/et.js
  src/i18n/fa.js
  src/i18n/fi.js
  src/i18n/fr.js
  src/i18n/hr.js
  src/i18n/hu.js
  src/i18n/it.js
  src/i18n/ja.js
  src/i18n/ko.js
  src/i18n/nb.js
  src/i18n/nl.js
  src/i18n/no.js
  src/i18n/pl.js
  src/i18n/pt-br.js
  src/i18n/ro.js
  src/i18n/ru.js
  src/i18n/sk.js
  src/i18n/sl.js
  src/i18n/sv.js
  src/i18n/tr.js
  src/i18n/ua.js
  src/i18n/vi.js
  src/i18n/zh-tw.js
  src/i18n/zh.js
Labels: CH: Changed

#1280 Always remove spaces from email and username
  src/__tests__/field/__snapshots__/email.test.js.snap
  src/__tests__/field/__snapshots__/username.test.js.snap
  src/__tests__/field/email.test.js
  src/__tests__/field/username.test.js
  src/field/email.js
  src/field/username.js
Labels: CH: Fixed

#1290 Update auth0.js and add flag to enable impersonation
  package.json
  src/__tests__/core/web_api/__snapshots__/p2_api.test.js.snap
  src/__tests__/core/web_api/p2_api.test.js
  src/core/web_api/p2_api.js
  yarn.lock
Labels: CH: Added

#1298 Fixing IE lack of support for `includes`
  src/quick-auth/actions.js
Labels: CH: Fixed

#1307 Fixed German translations
  src/i18n/de.js
Labels: CH: Fixed

#1295 Fix i18n ja
  src/i18n/ja.js
Labels: CH: Fixed

#1308 updating a0js with impersonation and token validation changes
  package.json
  src/__tests__/core/web_api/__snapshots__/p2_api.test.js.snap
  src/__tests__/core/web_api/p2_api.test.js
  src/core/web_api/p2_api.js
  yarn.lock
Labels: CH: Changed

#1309 Fix inconsistent state assignment
  src/__tests__/core/web_api/p2_api.test.js
  src/core/web_api/p2_api.js
Labels: CH: Fixed

#1321 Add jwksURI override option
  package.json
  src/__tests__/core/web_api/__snapshots__/helper.test.js.snap
  src/__tests__/core/web_api/__snapshots__/p2_api.test.js.snap
  src/__tests__/core/web_api/helper.test.js
  src/__tests__/core/web_api/p2_api.test.js
  src/core/web_api/helper.js
  yarn.lock
Labels: CH: Added
