Repository auth0/lock, pull requests merged in 2019-06, with the labels that each got.

#1663 Improve ssodata warning message
  src/core/remote_data.js
Labels: tiny

#1664 Fix password policy when using tenant connections
  src/__tests__/core/__snapshots__/tenant.test.js.snap
  src/__tests__/core/tenant.test.js
  src/core/tenant/index.js
Labels: CH: Fixed, small

#1671 Fix security vulnerabilities
  package.json
  yarn.lock
Labels: CH: Security, tiny

#1656 Add support for root level attributes
  README.md
  src/__tests__/connection/database/actions.test.js
  src/__tests__/connection/database/index.test.js
  src/connection/database/actions.js
  src/connection/database/index.js
Labels: CH: Added

#1681 use --trace when uploading to the cdn
  package.json
Labels: tiny

#1682 Add cdn digest
  package.json
Labels: tiny

#1683 Fix cdn upload
  package.json
  yarn.lock
Labels: tiny
