Repository auth0/lock, pull requests merged in 2019-10, with the labels that each got.

#1735 Relaxing the email validation
  src/__tests__/field/email.test.js
  src/field/email.js
  src/ui/input/email_input.jsx
Labels: CH: Changed, small

#1733 Fix social button interactions when terms have not been accepted
  css/index.styl
  src/__tests__/__snapshots__/auth_button.test.jsx.snap
  src/__tests__/engine/classic/__snapshots__/sign_up_screen.test.jsx.snap
  src/__tests__/field/__snapshots__/social_buttons_pane.test.jsx.snap
  src/__tests__/field/social_buttons_pane.test.jsx
  src/connection/database/actions.js
  src/engine/classic/sign_up_screen.jsx
  src/engine/passwordless/social_or_email_login_screen.jsx
  src/engine/passwordless/social_or_phone_number_login_screen.jsx
  src/field/social/social_buttons_pane.jsx
  src/i18n/en.js
  src/ui/button/auth_button.jsx
  support/index.html
Labels: CH: Changed

#1730 Map password_expired to password_change_required
  src/__tests__/core/index.test.js
  src/core/index.js
Labels: CH: Fixed

#1740 fix: Add missing property for finnish translation
  src/i18n/fi.js
Labels: CH: Added, [Goalie] Review Required, tiny

#1745 Reset .auth0-lock-form display to 'initial' for iPhone
  css/index.styl
Labels: CH: Fixed, tiny

#1742 Add a Lock event 'sso login'
  README.md
  src/connection/enterprise/actions.js
Labels: CH: Added, [Goalie] Review Required, tiny

#1744 added hungarian transalation for social_signup_needs_terms_acception
  src/i18n/hu.js
Labels: CH: Added, tiny
