Repository auth0/lock, pull requests merged in 2019-12, with the labels that each got.

#1759 [SDK-1141] Altered readme samples to remove ref to localstorage
  README.md
Labels: CH: Fixed, tiny

#1760 [SDK-1191] Lock social buttons now render as links instead of buttons
  css/index.styl
  src/__tests__/__snapshots__/auth_button.test.jsx.snap
  src/__tests__/auth_button.test.jsx
  src/ui/button/auth_button.jsx
Labels: CH: Fixed, tiny

#1764 Release 11.19.0
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: tiny

#1767 [SDK-980] Bumped auth0.js to 9.12.0
  package.json
  yarn.lock
Labels: CH: Security, tiny

#1765 add captcha support
  css/index.styl
  src/__tests__/field/login_pane.test.jsx
  src/connection/database/actions.js
  src/connection/database/login_pane.jsx
  src/core/index.js
  src/core/remote_data.js
  src/core/web_api.js
  src/core/web_api/helper.js
  src/core/web_api/p2_api.js
  src/field/captcha.js
  src/field/captcha/captcha_pane.jsx
  src/i18n/en.js
  src/i18n/es.js
  src/ui/input/captcha_input.jsx
  test/captcha.test.js
  test/helper/ui.js
Labels: CH: Added, medium

#1769 Release 11.20.0
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: tiny

#1770 Set the default token validation leeway to 60 sec
  package.json
  src/__tests__/core/web_api/__snapshots__/p2_api.test.js.snap
  src/__tests__/core/web_api/p2_api.test.js
  src/core/web_api/p2_api.js
  yarn.lock
Labels: CH: Fixed, small

#1773 Release 11.20.1
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: tiny

#1774 [CAUTH-277] prevent posting when captcha is required and empty
  src/connection/database/actions.js
  src/field/captcha/captcha_pane.jsx
  test/captcha.test.js
Labels: CH: Fixed
