Repository auth0/lock, pull requests merged in 2020-04, with the labels that each got.

#1839 [SDK-1413] Re-added scrollbars and fixed password strength popup clip issue
  css/index.styl
  src/__tests__/ui/box/__snapshots__/chrome.test.jsx.snap
  src/__tests__/ui/box/chrome.test.jsx
  src/ui/box/chrome.jsx
  src/ui/box/header.jsx
Labels: CH: Fixed, design, small

#1837 Add invalidHint to phoneNumberInput (fix issue #1836)
  src/__tests__/field/__snapshots__/phone_number_pane.test.jsx.snap
  src/engine/passwordless/social_or_phone_number_login_screen.jsx
  src/field/phone-number/phone_number_pane.jsx
  src/ui/input/phone_number_input.jsx
Labels: CH: Added, language file, small

#1842 Bumped auth0-js to 9.13.1
  package.json
  yarn.lock
Labels: CH: Changed, dependencies, tiny

#1841 Release v11.23.0
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: tiny

#1847 [ESD-5299] Bug with the special characters password hint
  css/index.styl
Labels: CH: Fixed, tiny

#1846 [ESD-5397] Fix header z-index
  css/index.styl
Labels: CH: Fixed, design, tiny

#1848 Upgraded dependencies from security advisories
  .circleci/config.yml
  package.json
  yarn.lock
Labels: CH: Security, dependencies, tiny

#1853 Revert "Upgraded dependencies from security advisories"
  .circleci/config.yml
  package.json
  yarn.lock
Labels: tiny
