Repository auth0/lock, pull requests merged in 2020-06, with the labels that each got.

#1876 Add !hostedLoginPage condition to redirect check
  src/__tests__/core/__snapshots__/web_api.test.js.snap
  src/__tests__/core/web_api.test.js
  src/core/web_api.js
Labels: CH: Fixed, tiny

#1878 [SDK-1556] Apply window height style to root document for Passwordless UI
  src/passwordless.js
Labels: CH: Fixed, tiny

#1879 Release 11.24.2
  CHANGELOG.md
  README.md
  bower.json
  package.json
  src/__tests__/core/__snapshots__/web_api.test.js.snap
  src/__tests__/core/web_api.test.js
Labels: tiny

#1882 Show the "Can't be blank" message under the password input
  css/index.styl
  src/__tests__/ui/input/__snapshots__/input_wrap.test.jsx.snap
  src/__tests__/ui/input/password_input.test.jsx
  src/ui/input/input_wrap.jsx
  src/ui/input/password_input.jsx
Labels: CH: Fixed, small

#1885 Allows i18n en lang override
  src/__tests__/i18n.test.js
  src/i18n.js
  test/captcha.test.js
Labels: CH: Fixed, small

#1888 [CAUTH-500] Reload recaptcha after wrong username or password
  src/__tests__/field/captcha.test.jsx
  src/__tests__/field/captcha/__snapshots__/recaptchav2.test.jsx.snap
  src/__tests__/field/captcha/recaptchav2.test.jsx
  src/field/captcha.js
  src/field/captcha/captcha_pane.jsx
  src/field/captcha/recaptchav2.js
  src/utils/createRef.js
Labels: CH: Fixed, small

#1865 Update Superagent to latest package.
  package.json
Labels: dependencies, tiny

#1889 Bump auth0-js to 9.13.3
  .circleci/config.yml
  package.json
  yarn.lock
Labels: CH: Changed, dependencies, tiny

#1890 [SDK-1756] Remove HTML5 novalidate attribute from Lock form
  src/__tests__/ui/box/__snapshots__/container.test.jsx.snap
  src/ui/box/container.jsx
Labels: CH: Changed, enhancement, tiny
