Repository auth0/lock, pull requests merged in 2020-12, with the labels that each got.

#1944 Update cs.js
  src/i18n/cs.js
Labels: CH: Changed, language file, small

#1948 [ESD-10373] Fix rendering of Lock inside popup on first open
  src/ui/box/header.jsx
Labels: CH: Fixed, bug, review:tiny

#1949 [ESD-10361] Fix password strength popup overflow issue
  DEVELOPMENT.md
  css/index.styl
  src/__tests__/ui/box/__snapshots__/chrome.test.jsx.snap
  src/__tests__/ui/box/chrome.test.jsx
  src/ui/box/chrome.jsx
  src/ui/box/header.jsx
Labels: CH: Fixed, design, review:small

#1950 Release 11.27.2
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: review:tiny
