Repository auth0/lock, pull requests merged in 2020-03, with the labels that each got.

#1815 [SDK-1389] Applied appearance styles for Bootstrap in Safari
  css/index.styl
Labels: CH: Fixed, bug, design, tiny

#1816 [SDK-1389] Release v11.22.3
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: tiny

#1818 [CAUTH-373] do not autologin the user if captcha is required
  src/connection/database/actions.js
  src/core/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: CH: Fixed

#1821 Release v11.22.4
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: tiny

#1828 add Azerbaijan language
  src/i18n/az.js
Labels: CH: Added, translations

#1835 add translate 'social_signup_needs_terms_acception' for japanese
  src/i18n/ja.js
Labels: CH: Fixed, tiny, translations
