Repository auth0/lock, pull requests merged in 2020-02, with the labels that each got.

#1790 [SDK-1300] Added a script to audit language files
  package.json
  scripts/lang-audit.js
  yarn.lock
Labels: small

#1791 [SDK-1300] Added missing translation keys for 6 EU languages
  src/i18n/da.js
  src/i18n/de.js
  src/i18n/it.js
  src/i18n/nb.js
  src/i18n/nl.js
  src/i18n/nn.js
  src/i18n/no.js
  src/i18n/sv.js
Labels: CH: Added, small

#1796 Release 11.21.1
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: tiny

#1799 Return results with signup success callback
  README.md
  src/connection/database/actions.js
  support/index.html
Labels: CH: Changed, tiny

#1802 [SDK-1374] Email input now uses type="email"
  src/__tests__/ui/input/__snapshots__/email_input.test.jsx.snap
  src/__tests__/ui/input/email_input.test.jsx
  src/ui/input/email_input.jsx
Labels: CH: Fixed, tiny

#1803 [SDK-1373] Added style rules to handle overflow and scroll
  css/index.styl
Labels: CH: Changed, design, tiny

#1801 [SDK-1361] Adjust styling for social buttons and Apple compliance
  css/index.styl
  src/i18n/en.js
Labels: CH: Changed, design, small

#1805 Release v11.22.0
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: tiny

#1808 [SDK-1361] Fix missing padding on social buttons
  css/index.styl
Labels: CH: Fixed, design, tiny

#1809 Release v11.22.1
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: tiny

#1810 Update cs.js - plural adjustments
  src/i18n/cs.js
Labels: CH: Fixed, language file, small

#1811 Change Sign in with Apple button background to full black
  css/social_icons.styl
Labels: CH: Changed, design, tiny

#1807 Update callback-cross-auth.html
  support/callback-cross-auth.html
Labels: tiny

#1812 Release v11.22.2
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: tiny
