Repository auth0/lock, pull requests merged in 2020-05, with the labels that each got.

#1845 Add support for google recaptcha
  src/__tests__/field/captcha.test.jsx
  src/__tests__/field/captcha/__snapshots__/recaptchav2.test.jsx.snap
  src/__tests__/field/captcha/recaptchav2.test.jsx
  src/field/captcha/captcha_pane.jsx
  src/field/captcha/recaptchav2.js
  src/ui/box/chrome.jsx
  test/captcha.test.js
Labels: CH: Added, enhancement, small

#1856 Fix send sms error event
  src/__tests__/connection/passwordless/__snapshots__/passwordless.actions.test.js.snap
  src/__tests__/connection/passwordless/passwordless.actions.test.js
  src/connection/passwordless/actions.js
Labels: CH: Fixed, tiny

#1859 Fix header height calculation for large titles
  css/index.styl
  src/__tests__/testUtils.js
  src/__tests__/ui/box/__snapshots__/chrome.test.jsx.snap
  src/__tests__/ui/box/__snapshots__/header.test.jsx.snap
  src/__tests__/ui/box/chrome.test.jsx
  src/__tests__/ui/box/header.test.jsx
  src/ui/box/chrome.jsx
  src/ui/box/header.jsx
Labels: CH: Fixed, design, small

#1862 Release v11.24.0
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: tiny

#1867 [ESD-6221] Remove CSS variable from header height calculation
  css/index.styl
  src/__tests__/core/__snapshots__/index.test.js.snap
  src/__tests__/core/index.test.js
  src/__tests__/ui/box/__snapshots__/chrome.test.jsx.snap
  src/__tests__/ui/box/__snapshots__/header.test.jsx.snap
  src/__tests__/ui/box/chrome.test.jsx
  src/__tests__/ui/box/header.test.jsx
  src/core.js
  src/core/actions.js
  src/core/index.js
  src/ui/box/chrome.jsx
  src/ui/box/header.jsx
Labels: CH: Fixed, small

#1868 Release 11.24.1
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: tiny

#1871 Add a basic DEVELOPMENT file to explain common scenarios
  DEVELOPMENT.md
Labels: documentation, tiny

#1874 Header height not updated when Lock dialog is closed and reopened
  src/__tests__/ui/box/__snapshots__/chrome.test.jsx.snap
  src/__tests__/ui/box/chrome.test.jsx
  src/ui/box/chrome.jsx
  src/ui/box/container.jsx
  src/ui/box/multisize_slide.js
Labels: small
