Repository auth0/lock, pull requests merged in 2020-08, with the labels that each got.

#1910 [SDK-1813] Send connection scope config to enterprise connections
  README.md
  src/__tests__/connection/enterprise/actions.test.js
  src/connection/enterprise/actions.js
Labels: CH: Added, small

#1912 i18n asset recovery
  src/i18n.js
Labels: CH: Fixed

#1914 Release v11.26.3
  CHANGELOG.md
  README.md
  bower.json
  package.json
  src/__tests__/connection/enterprise/__snapshots__/hrd_screen.test.js.snap
  src/__tests__/connection/passwordless/__snapshots__/ask_vcode.test.jsx.snap
Labels: tiny
