Repository auth0/lock, pull requests merged in 2020-07, with the labels that each got.

#1891 Release 11.24.4
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: tiny

#1893 Update issue templates + stalebot config
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/report-a-bug.md
  .github/stale.yml
Labels: documentation, small

#1892 [SDK-1738] Remove subtle transition on header element
  css/index.styl
Labels: CH: Fixed, design, tiny

#1894 Release v11.24.5
  CHANGELOG.md
  README.md
  bower.json
  package.json
  yarn.lock
Labels: tiny

#1895 Add 'bug' label to list of labels that are exempt from stalebot
  .github/stale.yml
Labels: tiny

#1896 [SDK-1710] Allow Lock to use connection display name field from client configuration file
  README.md
  src/__tests__/connection/enterprise/__snapshots__/quick_auth_screen.test.jsx.snap
  src/__tests__/connection/enterprise/quick_auth_screen.test.jsx
  src/__tests__/core/__snapshots__/index.test.js.snap
  src/connection/enterprise/quick_auth_screen.jsx
  src/core/client/index.js
  src/core/index.js
Labels: CH: Added, small

#1897 Release v11.25.0
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: tiny

#1899 Fix DEVELOPMENT.md formatting
  DEVELOPMENT.md
Labels: tiny

#1898 [SDK-1809] Connection display name is used even when no IdP domains are available
  src/__tests__/connection/enterprise/__snapshots__/quick_auth_screen.test.jsx.snap
  src/__tests__/connection/enterprise/quick_auth_screen.test.jsx
  src/connection/enterprise/quick_auth_screen.jsx
Labels: CH: Fixed, small

#1901 Release v11.25.1
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: tiny

#1900 [CAUTH-511] improve error handling on missing captcha
  css/index.styl
  package.json
  scripts/complete-translations.js
  src/__tests__/field/captcha/__snapshots__/recaptchav2.test.jsx.snap
  src/connection/database/actions.js
  src/core/index.js
  src/field/captcha.js
  src/field/captcha/captcha_pane.jsx
  src/field/captcha/recaptchav2.jsx
  src/i18n/af.js
  src/i18n/ar.js
  src/i18n/az.js
  src/i18n/bg.js
  src/i18n/ca.js
  src/i18n/cs.js
  src/i18n/da.js
  src/i18n/de.js
  src/i18n/el.js
  src/i18n/en.js
  src/i18n/es.js
  src/i18n/et.js
  src/i18n/fa.js
  src/i18n/fi.js
  src/i18n/fr.js
  src/i18n/he.js
  src/i18n/hr.js
  src/i18n/hu.js
  src/i18n/id.js
  src/i18n/it.js
  src/i18n/ja.js
  src/i18n/ko.js
  src/i18n/lt.js
  src/i18n/lv.js
  src/i18n/ms.js
  src/i18n/nb.js
  src/i18n/nl.js
  src/i18n/nn.js
  src/i18n/no.js
  src/i18n/pl.js
  src/i18n/pt-br.js
  src/i18n/pt.js
  src/i18n/ro.js
  src/i18n/ru.js
  src/i18n/sk.js
  src/i18n/sl.js
  src/i18n/sr.js
  src/i18n/sv.js
  src/i18n/tr.js
  src/i18n/ua.js
  src/i18n/uk.js
  src/i18n/vi.js
  src/i18n/zh-tw.js
  src/i18n/zh.js
  src/ui/input/captcha_input.jsx
  test/captcha.test.js
  yarn.lock
Labels: CH: Changed, large

#1904 [SDK-1284] Fix for "growing" tabs when repeatedly clicked
  css/index.styl
Labels: CH: Fixed, design, tiny

#1905 Release v11.26.0
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: tiny

#1907 fix issue #1906 - remove extension from import
  src/field/captcha/captcha_pane.jsx
Labels: CH: Fixed
