Repository auth0/lock, pull requests merged in 2020-10, with the labels that each got.

#1931 Respect showTerms option for passworless
  src/__tests__/connection/passwordless/__snapshots__/passwordless.test.js.snap
  src/__tests__/connection/passwordless/passwordless.test.js
  src/connection/passwordless/index.js
  src/engine/passwordless/social_or_email_login_screen.jsx
  src/engine/passwordless/social_or_phone_number_login_screen.jsx
Labels: CH: Fixed

#1939 Remove top padding from wrapper element
  css/index.styl
Labels: CH: Fixed, tiny

#1938 Remove javascript:void(0) from links that do not navigate
  src/__tests__/connection/passwordless/__snapshots__/email_sent_confirmation.test.jsx.snap
  src/__tests__/field/__snapshots__/vcode_pane.test.jsx.snap
  src/connection/database/login_pane.jsx
  src/connection/database/login_sign_up_tabs.jsx
  src/connection/passwordless/email_sent_confirmation.jsx
  src/field/vcode/vcode_pane.jsx
  src/ui/pane/quick_auth_pane.jsx
Labels: CH: Fixed

#1940 Release 11.27.1
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: tiny
