Repository auth0/lock, pull requests merged in 2021-06, with the labels that each got.

#1996 Update auth0-js + node-fetch
  package.json
  yarn.lock
Labels: CH: Security, review:tiny

#2000 Update fa.js
  src/i18n/fa.js
Labels: CH: Changed, language file, review:small

#2003 Release 11.30.1
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: review:tiny

#2006 [ESD-13941] Implement a DOMPurify hook to enable target attributes on links
  src/__tests__/i18n.test.js
  src/core.js
  src/sanitizer.js
Labels: CH: Changed, review:small

#2010 Prepare v11.30.3
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: review:tiny
