Repository auth0/lock, pull requests merged in 2021-03, with the labels that each got.

#1968 Disable form submit manually for passwordless Safari
  src/__tests__/ui/box/container.test.jsx
  src/ui/box/container.jsx
Labels: review:small

#1969 Release v11.28.1
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: review:tiny

#1971 Remove padding from screen tabs
  css/index.styl
Labels: CH: Fixed, design, review:tiny

#1972 Run npm audit and reimport yarn lock file
  yarn.lock
Labels: dependencies

#1974 Remove line breaks from passwordless vcode entry instructions
  src/i18n/af.js
  src/i18n/az.js
  src/i18n/bg.js
  src/i18n/ca.js
  src/i18n/da.js
  src/i18n/de.js
  src/i18n/el.js
  src/i18n/es.js
  src/i18n/et.js
  src/i18n/fa.js
  src/i18n/fi.js
  src/i18n/fr.js
  src/i18n/hr.js
  src/i18n/id.js
  src/i18n/it.js
  src/i18n/lt.js
  src/i18n/lv.js
  src/i18n/ms.js
  src/i18n/nb.js
  src/i18n/nl.js
  src/i18n/nn.js
  src/i18n/no.js
  src/i18n/pl.js
  src/i18n/pt-br.js
  src/i18n/pt.js
  src/i18n/ro.js
  src/i18n/ru.js
  src/i18n/sk.js
  src/i18n/sl.js
  src/i18n/sr.js
  src/i18n/sv.js
  src/i18n/tr.js
  src/i18n/ua.js
  src/i18n/uk.js
  src/i18n/vi.js
  src/i18n/zh-tw.js
  src/i18n/zh.js
Labels: CH: Fixed, language file, review:small

#1975 Fixes typo "assests" to "assets"
  README.md
Labels: CH: Fixed, documentation, review:tiny
