Repository auth0/lock, pull requests merged in 2021-04, with the labels that each got.

#1977 [SDK-2412] Add event for SSO data fetch
  README.md
  src/__tests__/core/remote_data.test.js
  src/core.js
  src/core/remote_data.js
  support/index.html
Labels: CH: Added, review:small

#1978 [ESD-12716] fix issue with recaptcha in mobile
  src/field/captcha/recaptchav2.jsx
Labels: CH: Fixed

#1976 [SDK-2306] Add login and signup hooks
  .vscode/launch.json
  README.md
  src/__tests__/connection/database/actions.test.js
  src/__tests__/core/__snapshots__/index.test.js.snap
  src/__tests__/core/actions.test.js
  src/connection/database/actions.js
  src/core.js
  src/core/actions.js
  src/core/index.js
  src/ui/box/chrome.jsx
  support/index.html
  test/hooks.test.js
  yarn.lock
Labels: CH: Added, review:medium

#1980 Release v11.29.0
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: review:tiny

#1982 Align stalebot config with other SDKs
  .github/stale.yml
Labels: review:tiny

#1983 fix ESD-12716: move CSS display override to render function to fix recaptcha on sign-up
  src/field/captcha/recaptchav2.jsx
Labels: CH: Fixed, review:small

#1985 Release v11.29.1
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: review:small

#1981 [SDK-2383] Support custom passwordless connections
  README.md
  src/__tests__/connection/passwordless/__snapshots__/passwordless.actions.test.js.snap
  src/__tests__/connection/passwordless/passwordless.actions.test.js
  src/__tests__/core/__snapshots__/index.test.js.snap
  src/connection/passwordless/actions.js
  src/core/index.js
Labels: CH: Added, review:small

#1987 Feature/recaptcha enterprise cauth 964
  src/__tests__/field/captcha/recaptchav2.test.jsx
  src/field/captcha/recaptcha.jsx
Labels: review:tiny

#1988 [ESD-12716]fix recaptcha on mobile when lang is not English
  src/field/captcha/recaptcha.jsx
Labels: CH: Fixed, review:small

#1989 Release v11.30.0
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: review:tiny
