Repository auth0/lock, pull requests merged in 2021-07, with the labels that each got.

#2013 SL - Updated Dutch translations
  src/i18n/nl.js
Labels: CH: Fixed, language file, review:small

#2014 Release 11.30.4
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: review:tiny

#2016 Add `signUpFieldsStrictValidation` description to the readme
  README.md
Labels: documentation, review:tiny
