Repository auth0/lock, pull requests merged in 2021-09, with the labels that each got.

#2029 [SDK-2708] Use configured domain for client assets download
  package.json
  src/__tests__/core/index.test.js
  src/core/index.js
  test/tenantinfo.test.js
  yarn.lock
Labels: CH: Changed, review:small

#2030 Inline util.format and replace usage of global
  LICENSE
  package.json
  src/__tests__/connection/enterprise/__snapshots__/hrd_screen.test.js.snap
  src/__tests__/connection/passwordless/__snapshots__/ask_vcode.test.jsx.snap
  src/__tests__/core/web_api.test.js
  src/__tests__/core/web_api/helper.test.js
  src/__tests__/setup-tests.js
  src/__tests__/utils/format.test.js
  src/browser.js
  src/connection/database/index.js
  src/core/actions.js
  src/i18n.js
  src/store/index.js
  src/sync.js
  src/ui/box.js
  src/ui/box/chrome.jsx
  src/ui/box/container.jsx
  src/ui/box/header.jsx
  src/ui/input/password/password_strength.jsx
  src/utils/cdn_utils.js
  src/utils/format.js
  support/design/control.jsx
  test/acceptance_test_utils.js
  test/helper/ui.js
  test/out-of-date/gravatar/web_api.js
  yarn.lock
Labels: CH: Fixed, review:medium

#2032 Use the new release automation solution
  .shiprc
  package.json
  scripts/release.sh
Labels: review:tiny

#2033 Remove Bower publishing from Jenkins CI script
  scripts/ci.sh
Labels: review:tiny

#2041 Release configuration
  .circleci/config.yml
  .shiprc
Labels: review:tiny

#2042 [chore] Build config + dependency updates
  .circleci/config.yml
  .eslintrc.json
  .prettierignore
  .prettierrc.yaml
  .vscode/settings.json
  package.json
  scripts/ci.sh
  src/i18n/cs.js
  yarn.lock
Labels: dependencies, review:small
