Repository auth0/lock, pull requests merged in 2021-01, with the labels that each got.

#1953 Wording and spelling fixes to bg.js
  src/i18n/bg.js
Labels: language file

#1954 An option to hide username in signup view
  README.md
  src/__tests__/engine/classic/__snapshots__/sign_up_pane.test.jsx.snap
  src/__tests__/engine/classic/sign_up_pane.test.jsx
  src/connection/database/actions.js
  src/connection/database/index.js
  src/engine/classic/sign_up_pane.jsx
Labels: CH: Added

#1955 Release v11.28.0
  CHANGELOG.md
  README.md
  bower.json
  package.json
Labels: review:tiny

#1960 Upgrade trim version to fix security issue
  package.json
  yarn.lock
Labels: CH: Security, review:tiny
